version: 2
jobs:
  build_linux:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      # - run: yarn test
      # Build app
      - run: yarn build && yarn dist:linux

  build_windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      # - run: yarn test
      - run: yarn build && yarn dist:win

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_windows
