version: 2
jobs:
  build_linux:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      # - run: yarn test
      # Build app
      - run: yarn build && yarn dist:linux

  build_windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      # - run: yarn test
      - run: yarn build && yarn dist:win

  build_macos:
    macos:
      xcode: '10.0.0'
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      # - run: yarn test
      # Signing
      # - run: security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      # - run: security default-keychain -s build.keychain
      # - run: security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      # - run: echo $KEYSTORE | base64 --decode - > keystore.p12
      # - run: security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign
      - run: yarn build && yarn dist:mac

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_windows
      - build_macos
